/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGithubAppCallbackRouteImport } from './routes/api/github-app/callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OwnerRepoBranchRouteImport } from './routes/$owner/$repo/$branch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubAppCallbackRoute = ApiGithubAppCallbackRouteImport.update({
  id: '/api/github-app/callback',
  path: '/api/github-app/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoBranchRoute = OwnerRepoBranchRouteImport.update({
  id: '/$owner/$repo/$branch',
  path: '/$owner/$repo/$branch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$owner/$repo/$branch': typeof OwnerRepoBranchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github-app/callback': typeof ApiGithubAppCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$owner/$repo/$branch': typeof OwnerRepoBranchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github-app/callback': typeof ApiGithubAppCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$owner/$repo/$branch': typeof OwnerRepoBranchRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/github-app/callback': typeof ApiGithubAppCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$owner/$repo/$branch'
    | '/api/auth/$'
    | '/api/github-app/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$owner/$repo/$branch' | '/api/auth/$' | '/api/github-app/callback'
  id:
    | '__root__'
    | '/'
    | '/$owner/$repo/$branch'
    | '/api/auth/$'
    | '/api/github-app/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRepoBranchRoute: typeof OwnerRepoBranchRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGithubAppCallbackRoute: typeof ApiGithubAppCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github-app/callback': {
      id: '/api/github-app/callback'
      path: '/api/github-app/callback'
      fullPath: '/api/github-app/callback'
      preLoaderRoute: typeof ApiGithubAppCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/$branch': {
      id: '/$owner/$repo/$branch'
      path: '/$owner/$repo/$branch'
      fullPath: '/$owner/$repo/$branch'
      preLoaderRoute: typeof OwnerRepoBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRepoBranchRoute: OwnerRepoBranchRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGithubAppCallbackRoute: ApiGithubAppCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
